/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zckhgl.biodatapert3;

/**
 *
 * @author excee
 */
public class BioData extends javax.swing.JFrame {

    String nama, nim, alamat, domisili, prodi, hobby, gender;

    /**
     * Creates new form BioData
     */
    public BioData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXToutput = new javax.swing.JLabel();
        TXTtitle = new javax.swing.JLabel();
        TxtNama = new javax.swing.JLabel();
        TFnama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TFnim = new javax.swing.JTextField();
        TXTgender = new javax.swing.JLabel();
        CMBgender = new javax.swing.JComboBox<>();
        TXTprodi = new javax.swing.JLabel();
        TXTalamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaAlamat = new javax.swing.JTextArea();
        TXThobby = new javax.swing.JLabel();
        TFhobby = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaOutput = new javax.swing.JTextArea();
        BTNsubmit = new javax.swing.JButton();
        TXTdomisili = new javax.swing.JLabel();
        TFdomisili = new javax.swing.JTextField();
        CMBprodi = new javax.swing.JComboBox<>();
        BTNhapus = new javax.swing.JButton();

        TXToutput.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        TXToutput.setText("Output");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TXTtitle.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        TXTtitle.setText("Biodata");

        TxtNama.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        TxtNama.setText("Nama");

        TFnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnamaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel1.setText("NIM");

        TFnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnimActionPerformed(evt);
            }
        });

        TXTgender.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        TXTgender.setText("Gender");

        CMBgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Laki-Laki", "Perempuan" }));

        TXTprodi.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        TXTprodi.setText("Prodi");

        TXTalamat.setText("Alamat");

        AreaAlamat.setColumns(20);
        AreaAlamat.setRows(5);
        jScrollPane1.setViewportView(AreaAlamat);

        TXThobby.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        TXThobby.setText("Hobby");

        TFhobby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFhobbyActionPerformed(evt);
            }
        });

        AreaOutput.setColumns(20);
        AreaOutput.setRows(5);
        AreaOutput.setText("Output\n");
        jScrollPane2.setViewportView(AreaOutput);

        BTNsubmit.setText("SUBMIT!");
        BTNsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsubmitActionPerformed(evt);
            }
        });

        TXTdomisili.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        TXTdomisili.setText("Domisili");

        CMBprodi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Teknik Informatika", "Sistem Komputer", "Manajemen", "International Business Management", "Desain Komunikasi Visual" }));

        BTNhapus.setText("HAPUS!");
        BTNhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(TXTtitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTNsubmit)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TXTalamat)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(TXTgender)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CMBgender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TXTprodi)
                                    .addGap(18, 18, 18)
                                    .addComponent(CMBprodi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TxtNama)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TFnama))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TXTdomisili)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TFdomisili, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TXThobby)
                                        .addComponent(jLabel1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TFnim, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                        .addComponent(TFhobby))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BTNhapus)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(TXTtitle)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNama)
                    .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTprodi)
                    .addComponent(TXTdomisili, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFdomisili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBprodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTgender)
                    .addComponent(CMBgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXThobby)
                    .addComponent(TFhobby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTalamat)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNsubmit)
                    .addComponent(BTNhapus))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnamaActionPerformed

    private void BTNsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsubmitActionPerformed
        // TODO add your handling code here:
        nama = TFnama.getText();
        alamat = AreaAlamat.getText();
        gender = CMBgender.getSelectedItem().toString();
        nim = TFnim.getText();
        hobby = TFhobby.getText();
        domisili = TFdomisili.getText();
        prodi = CMBprodi.getSelectedItem().toString();

        AreaOutput.setText("Nama: \t = " + nama + "\nGender \t= " + gender + "\nNIM \t= " + nim + "\nProdi \t= " + prodi + "\nDomisili \t= " + domisili + "\nHobby \t= " + hobby + "\nAlamat \t= " + alamat);

    }//GEN-LAST:event_BTNsubmitActionPerformed

    private void TFnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnimActionPerformed

    private void TFhobbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFhobbyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFhobbyActionPerformed

    private void BTNhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNhapusActionPerformed
        // TODO add your handling code here:
        TFnim.setText("");
        TFnama.setText("");
        AreaAlamat.setText("");
        TFdomisili.setText("");
        TFhobby.setText("");
        AreaOutput.setText("");
        CMBgender.setSelectedItem("None");
        CMBprodi.setSelectedItem("None");
        
        
    }//GEN-LAST:event_BTNhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BioData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BioData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BioData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BioData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BioData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaAlamat;
    private javax.swing.JTextArea AreaOutput;
    private javax.swing.JButton BTNhapus;
    private javax.swing.JButton BTNsubmit;
    private javax.swing.JComboBox<String> CMBgender;
    private javax.swing.JComboBox<String> CMBprodi;
    private javax.swing.JTextField TFdomisili;
    private javax.swing.JTextField TFhobby;
    private javax.swing.JTextField TFnama;
    private javax.swing.JTextField TFnim;
    private javax.swing.JLabel TXTalamat;
    private javax.swing.JLabel TXTdomisili;
    private javax.swing.JLabel TXTgender;
    private javax.swing.JLabel TXThobby;
    private javax.swing.JLabel TXToutput;
    private javax.swing.JLabel TXTprodi;
    private javax.swing.JLabel TXTtitle;
    private javax.swing.JLabel TxtNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
